### ISSUE TITLE
Problems with summoning minions from specific staff

### ISSUE THREAD

**Issue by venomuspool** [Andenis-Bu/LPAutoSummon#1]
Expixive Staff - Fargo's Souls Mod, when using it, the summoned creature occupies 0.33 slots, and in fact 13 creatures are summoned out of ~39 possible (when checking I had 13 slots for minions), also this weapon is specific because the summoned creatures self-destruct after collision with the enemy, and thus the slots of minions are released, is it possible to make it so that the summoned creatures are summoned depending on the available slots
Sorry for machine translator.
![image](https://github.com/Andenis-Bu/LPAutoSummon/assets/95861816/defc476f-87b5-46cc-83a7-5a693dad0269)

**Comment by Andenis-Bu** [comment]
Hey @venomuspool  thank you for submitting you report. I'll look in to it but I can't make any promises, as implementing logic for mod specific scenarios like this one can become challenging, but I'll see what I can do.

**Comment by Andenis-Bu** [comment]
@venomuspool I believe I have a way to fix it, or at the very least have it summon all 39 minions. But now the problem is that, my mod skips the summoning animation and also doesn't use mana for summoning, so your minions would be going of like a machine gun during a boss battle if I made them respawn when there are free slots. So it would just make your summoner item insanely over powered.

**Comment by Andenis-Bu** [comment]
Ok so you can read more about the change on the workshop page, but I added support for minions that use less than 1 slot, but instead of re-summoning them as they disappear I added the ability to re-summon all of them when when using the item with mouse click.
